# Generated by Django 4.0.4 on 2022-07-19 00:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0002_alter_category_subscribers_subcriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcriber',
            new_name='Subscriber',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='subcribed_category',
            new_name='subscribed_category',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='subcriber_user',
            new_name='subscriber_user',
        ),
    ]
